spring: 
  profiles:
    active:
    - dev
    
eureka: 
  client: # 将客户端注册进eureka服务列表内
    service-url: 
      defaultZone: http://192.168.56.1:7001/eureka/
      
      
--- # 测试环境      
spring: 
  profiles:
    active:
    - test
    
eureka: 
  client: # 将客户端注册进eureka服务列表内
    service-url: 
      defaultZone: http://192.168.56.1:7001/eureka/

--- # 生产环境    
spring: 
  profiles:
    active:
    - prod
    
eureka: 
  client: # 将客户端注册进eureka服务列表内
    service-url: 
      defaultZone: http://192.168.56.1:7001/eureka/