spring: 
  profiles:
    active:
    - dev
    
--- # 开发环境
server:
  port: 8000
spring: 
   profiles: dev
   application: 
    name: etcp-client-microservice-config-center
    
eureka: 
  client: # 将客户端注册进eureka服务列表内
    region: eurekaRegion
    availabilityZones:
      eurekaRegion: local_dev
    service-url: 
      defaultZone: http://localhost:7001/eureka
    fetchRemoteRegionsRegistry: eurekaRegion
  instance:
    appname: microservice-provider
    instance-id: microservice-provider
    prefer-ip-address: true


  
--- # 测试环境
server:
  port: 8001
spring: 
   profiles: test
   application: 
    name: etcp-client-microservice-config-center
 
eureka: 
  client: # 将客户端注册进eureka服务列表内
    region: eurekaRegion
    availabilityZones:
      eurekaRegion: local_test
    service-url: 
      defaultZone: http://localhost:7001/eureka
    fetchRemoteRegionsRegistry: eurekaRegion
  instance:
    appname: microservice-provider
    virtual-host-name: ${eureka.instance.appname}
    secure-virtual-host-name: ${eureka.instance.appname}
    instance-id: microservice-provider
    home-page-url-path: /microservice-provider/
    status-page-url-path: /microservice-provider/health
    prefer-ip-address: true
    metadata-map:
      zone: local_test
      line: iop
      contextPath: microservice-provider
      version: v1_1_0
  
--- # 发布环境
server:
  port: 8002
spring: 
   profiles: prod
   application: 
    name: etcp-client-microservice-config-center
   
 
eureka: 
  client: # 将客户端注册进eureka服务列表内
    region: eurekaRegion
    availabilityZones:
      eurekaRegion: local_prod
    service-url: 
      defaultZone: http://localhost:7001/eureka
    fetchRemoteRegionsRegistry: eurekaRegion
  instance:
    appname: iop.prod.v1_1_0
    virtual-host-name: ${eureka.instance.appname}
    secure-virtual-host-name: ${eureka.instance.appname}
    instance-id: microservice-provider
    home-page-url-path: /microservice-provider/
    status-page-url-path: /microservice-provider/health
    prefer-ip-address: true
    metadata-map:
      zone: local_prod
      line: iop
      contextPath: microservice-provider
      version: v1_1_0
  
  